openapi: 3.0.0
info:
  title: Pokemon Battle API
  description: API for managing Pokemon battles and trainer interactions
  version: 1.0.0

servers:
  - url: https://your-project.supabase.co/functions/v1
    description: Supabase Edge Functions

paths:
  /combats:
    post:
      summary: Start a new combat
      description: Initiates a new battle between a player and an NPC trainer
      tags:
        - Combat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                playerId:
                  type: string
                  format: uuid
                npcTrainerId:
                  type: string
                  format: uuid
      responses:
        '201':
          description: Combat created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Combat'
        '400':
          description: Invalid request
        '404':
          description: Trainer or Pokemon not found

    get:
      summary: Get combat details
      description: Retrieves the details of an ongoing or completed combat
      tags:
        - Combat
      parameters:
        - name: combatId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Combat details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Combat'
        '404':
          description: Combat not found

  /combats/action:
    post:
      summary: Perform combat action
      description: Execute an action during combat (attack, switch Pokemon, etc.)
      tags:
        - Combat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CombatAction'
      responses:
        '200':
          description: Action performed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombatResult'
        '400':
          description: Invalid action
        '404':
          description: Combat not found

components:
  schemas:
    Combat:
      type: object
      properties:
        id:
          type: string
          format: uuid
        player:
          $ref: '#/components/schemas/Fighter'
        npcTrainer:
          $ref: '#/components/schemas/Fighter'
        status:
          type: string
          enum: [ACTIVE, FINISHED]
        winner:
          type: string
          nullable: true
        turns:
          type: array
          items:
            $ref: '#/components/schemas/CombatAction'

    Fighter:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        currentPokemon:
          $ref: '#/components/schemas/Pokemon'
        pokemons:
          type: array
          items:
            $ref: '#/components/schemas/Pokemon'

    Pokemon:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        level:
          type: integer
        hp:
          type: integer
        currentHp:
          type: integer
        attack:
          type: integer
        defense:
          type: integer
        speed:
          type: integer
        moves:
          type: array
          items:
            $ref: '#/components/schemas/Move'

    Move:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        power:
          type: integer
        accuracy:
          type: integer
        type:
          type: string

    CombatAction:
      type: object
      properties:
        combatId:
          type: string
          format: uuid
        actionType:
          type: string
          enum: [ATTACK, SWITCH_POKEMON]
        fighterId:
          type: string
          format: uuid
        moveId:
          type: string
          format: uuid
        targetPokemonId:
          type: string
          format: uuid

    CombatResult:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        damage:
          type: integer
        combat:
          $ref: '#/components/schemas/Combat'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

tags:
  - name: Combat
    description: Operations related to Pokemon battles 